language: julia

os:
  - linux
  - osx
  - windows

julia:
  - 1.0
  - 1.1
  - 1.2
  - 1.3
  - nightly

matrix:
  allow_failures:
    - julia: nightly

notifications:
  email:
    recipients: dominique.orban@gmail.com
    on_success: never
    on_failure: change

branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/ # tags

after_success:
  - julia -e 'using Pkg; cd(Pkg.dir("QuadraticModels")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  - julia -e 'using Pkg; cd(Pkg.dir("QuadraticModels")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
